# -*- coding: utf-8 -*-
"""Boxoffice Data .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aq5XnO1_Mb2NTbFrcnoDakhTjR7QS4TM
"""

!pip install boxoffice_api

import pandas as pd
from datetime import datetime, timedelta
from boxoffice_api import BoxOffice
import time

box = BoxOffice(outputformat="DF")

START_YEAR = 2009
END_YEAR = 2025


start_date = datetime(START_YEAR, 1, 1)
end_date = datetime(END_YEAR, 12, 31)


all_days = []

current_date = start_date
while current_date <= end_date:
    date_str = current_date.strftime("%Y-%m-%d")
    try:
        df = box.get_daily(date=date_str)
        df["date"] = date_str
        all_days.append(df)
        print(f"✅ Pulled data for {date_str} ({len(df)} records)")
    except Exception as e:
        print(f"⚠️ Skipped {date_str}: {e}")
    time.sleep(1.5)
    current_date += timedelta(days=1)

if all_days:
    combined = pd.concat(all_days, ignore_index=True)
    combined.to_csv(f"boxoffice_{START_YEAR}-{END_YEAR}.csv", index=False)
    print(f"📁 Saved to boxoffice_{START_YEAR}-{END_YEAR}.csv")
else:
    print("No data collected!")